# Github composite action to report on code size changes
name: Report binary size changes on PR
description: |
  Report on code size changes resulting from a PR as a comment on the PR
  (accessed via context).
inputs:
   reference:
    description: The size in bytes of the reference binary (base of PR).
    required: true
   updated:
    description: The size in bytes of the updated binary (head of PR).
    required: true
runs:
  using: composite
  steps:
    - name: Post a PR comment if the size has changed
      uses: actions/github-script@v6
      env:
        SIZE_REFERENCE: ${{ inputs.reference }}
        SIZE_UPDATED: ${{ inputs.updated }}
      with:
        script: |
          const reference = process.env.SIZE_REFERENCE;
          const updated = process.env.SIZE_UPDATED;

          if (!(reference > 0)) {
            core.setFailed(`Reference size invalid: ${reference}`);
            return;
          }

          if (!(updated > 0)) {
            core.setFailed(`Updated size invalid: ${updated}`);
            return;
          }

          const formatter = Intl.NumberFormat("en", {useGrouping: "always"});

          const updated_str = formatter.format(updated);
          const reference_str = formatter.format(reference);

          const diff = updated - reference;
          const diff_pct = (updated / reference) - 1;

          const diff_str = Intl.NumberFormat("en", {
            useGrouping: "always",
            sign: "exceptZero"
          }).format(diff);

          const diff_pct_str = Intl.NumberFormat("en", {
            style: "percent",
            useGrouping: "always",
            sign: "exceptZero",
            maximumFractionDigits: 2
          }).format(diff_pct);

          if (diff !== 0) {
            // The body is created here and wrapped so "weirdly" to avoid whitespace at the start of the lines,
            // which is interpreted as a code block by Markdown.
            const body = `Below is the size of a hello-world Rust program linked with libstd with backtrace.

          Original binary size: **${reference_str} B**
          Updated binary size: **${updated_str} B**
          Difference: **${diff_str} B** (${diff_pct_str})`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
          }
